export const EDIT_NAME = 'editName'
export const TOGGLE_SIGNIN = 'toggleSignin'
export const FETCH_DATA_REQUEST = 'fetchDataRequest'
export const FETCH_DATA_SUCCESS = 'fetchDataSuccess'
export const FETCH_DATA_FAILED = 'fetchDataFailed'